{% set data = load_setup_py_data() %}
{% set version = data.get('version')  %}

package:
  name: benchcab
  version: {{ version }}

source:
    path: ..


build:
    script: "{{ PYTHON }} -m pip install . --no-deps"
    noarch: python
    number: {{ GIT_DESCRIBE_NUMBER }}


requirements:
    host:
        - python >=3.9
        - pip
        - pbr
    run:
        - python >=3.9
        - netCDF4
        - PyYAML
        - f90nml
        - flatdict
        - cerberus >=1.3.5
        - gitpython
